language: java
cache:
  directories:
    - $HOME/.m2
env:
  - TEST_SUITE=integration-test
  - TEST_SUITE=unit-test

script:
  - mvn verify -B -P ${TEST_SUITE}

matrix:
  include:
  - jdk: openjdk8
  - jdk: oraclejdk9
    before_install:
        # The OpenJDK9's CA bundle is outdated, so we're using the system's ones.
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  # - jdk: openjdk11 (default)
  - jdk: openjdk12
