# 
# This is a JPSONIC boot configuration sample in Synology DS220+ or in Linux with UPnP.
# You can easily start Jpsonic by changing the volume, port and so on.
#
# usege: 
#   docker-compose -f production.synology.yml up -d
#

version: '3.9'
services:
  app:
    image: 'jpsonic/jpsonic:latest'
    container_name: 'jpsonic'
    network_mode: 'host'
    hostname: 'SynologyNAS'
    pid: host

    # This image is automatically updated by watchtower.
    # See docker-compose.watchtower.yml
    labels:
     - "com.centurylinklabs.watchtower.enable=true"

    volumes:
     # <host>:<internal>
     # Please rewrite "the path of host" appropriately.
     - '/volume1/docker/jpsonic-data:/jpsonic/data'
     - '/volume1/Music:/jpsonic/music'
     - '/volume1/Podcasts:/jpsonic/podcasts'
     - '/volume1/Playlists:/jpsonic/playlists'

     # If you want to add a large number of music folders, please add more volumes
     # - '/volume1/Music2:/jpsonic/music2'
     # - '/volume1/Music3:/jpsonic/music3'

    deploy:
      resources:
        limits:

          # Jpsonic container is limited to 1Gb so that it can run on DS220+'s standard memory.
          # Xmx512m is assigned by default, but with these settings,
          # it is assumed that 100,000 songs can be scanned for music only.
          # For larger libraries, increase Xmx and this setting by the same value.
          # ie) memory: 1.5g at -Xmx1024
          memory: 1g

    environment:

     # Set the jpsonic and upnp ports.
     # Containers share the host networking name space,
     # so be careful not to overlap with existing ports.
     JPSONIC_PORT: '4040'
     UPNP_PORT: '4041'

     # Set the appropriate UID/GID.
     USER_ID: '0'
     GROUP_ID: '0'

     # Please specify the appropriate timezone
     TIME_ZONE: 'Asia/Tokyo'

     # Jpsonic context path.
     CONTEXT_PATH: '/'

     # Whether to log the logo at startup. [OFF|CONSOLE|LOG]
     BANNER_MODE: 'OFF'

     # Granularity of output logs. [ERROR|WARN|INFO|DEBUG|TRACE]
     LOG_LEVEL: 'WARN'

     # Whether to scan at startup. False is recommended for Docker.
     SCAN_ON_BOOT: 'false'

     # If false, use the logical font of JRE (JDK) for Cover Art.
     # If true, preferentially use embedded fonts.
     EMBEDDED_FONT: 'false'

     # You can override the MIME of DSD according to your device.
     MIME_DSF: 'audio/x-dsd'
     MIME_DFF: 'audio/x-dsd'

     # Specify the appropriate Java options.
     # Currently, Jpsonic will not require extremely large memory.
     # If you are using 32 bit OS please specify -Xmx256m
     JAVA_OPTS: '-Xmx512m'

     #　Option example when using JMX. The "ea" tag image is required to use JMX.
     #　For VisualVM, you need to specify the port in File-Add JMX Connection.
     #　e.g. localhost:3333
     #　
     #JAVA_OPTS: >
     #  -Xmx512m
     #  -Dcom.sun.management.jmxremote
     #  -Dcom.sun.management.jmxremote.port=3333
     #  -Dcom.sun.management.jmxremote.rmi.port=3333
     #  -Dcom.sun.management.jmxremote.local.only=false
     #  -Dcom.sun.management.jmxremote.ssl=false
     #  -Dcom.sun.management.jmxremote.authenticate=false
     #  -Djava.rmi.server.hostname=localhost

    # Usually no need to change.
    # Unlike other Sonic servers, Jpsonic has a graceful shutdown implemented.
    # After receiving the 'kill 15' of Docker message, it will phase out, and finnaly shut down the database.
    # In case of emergency shutdown during critical processing,
    # there may be a wait time of up to 30 seconds to protect data.
     TINI_SUBREAPER: 'true'
    stop_grace_period: '30s'
